export default [
  {
    title: "Сайт бизнес компании",
    descr: 'Сайт для бизнес компании "GLOBALTEAM". Нужно было реализовать красивый и анимированный сайт. На сайте было много элементов декора так же была использована библиотека "AOS" анимация.',
    price: "6.000",
    img: require("@/assets/img/portfolio/4.jpg"),
    link: "project/GlobalTeam/index.html",
    site: "landing",
  },
  {
    title: "Сайт магазина одежды",
    descr:
      'Сайт для магазина одежды "Tramontana". Стояла задача обновить 3 страницы <a href="project/Tramontana/index.html">Главная,</a> <a href="project/Tramontana/card-page.html">Карточка товара</a> и <a href="project/Tramontana/catalog.html">Каталог</a>.',
    price: "15.000",
    img: require("@/assets/img/portfolio/9.jpg"),
    link: "project/Tramontana/index.html",
    site: "shop",
  },
  {
    title: "Сайт образовательной платформы",
    descr: 'Сайт образовательной платформы "XOD". Нужно было сделать сайт адаптивным под все разрешения экранов что и было реализовано.',
    price: "5.000",
    img: require("@/assets/img/portfolio/10.jpg"),
    link: "project/XOD/index.html",
    site: "corp",
  },
  {
    title: "Сайта знакомств",
    descr: 'Сайта знакомств "Alastora". Основное требование нужно было реализовать слайдер на весь сайт.',
    price: "6.500",
    img: require("@/assets/img/portfolio/1.jpg"),
    link: "project/Alastora/index.html",
    site: "landing",
  },
  {
    title: "Сайт Баня Лукоморье",
    descr: 'На сайте было реализовано 2 слайдера библиотека "Slick slider", 3 модальных окна на библиотеке "JQuery" также 5 аккордеонов.',
    price: "4.000",
    img: require("@/assets/img/portfolio/2.jpg"),
    link: "project/bathhouse/index.html",
    site: "landing",
  },
  {
    title: "Сайт по подбору мероприятий",
    descr:
      'Сайт по подбору мероприятий "Eventplace". Было сверстано 3 страницы <a href="project/eventplace/index.html">Главная,</a> <a href="project/eventplace/catalog/1.html">Каталог</a> и <a href="project/eventplace/private-office.html">Личный кабинет</a> верстка велась использование библиотеки Bootstrap.',
    price: "6.000",
    img: require("@/assets/img/portfolio/3.jpg"),
    link: "project/eventplace/index.html",
    site: "corp",
  },
  {
    title: "Сайт платформы анализа",
    descr:
      'Сайт платформы анализа "Neurometrix". Было сверстано 6 страниц и натянуто на Wordpress для удобного управления сайтом. Особенностью сайта было то что надо было написать кастомный калькулятор.',
    price: "35.700",
    img: require("@/assets/img/portfolio/14.jpg"),
    link: "https://neurometrix.ai/",
    site: "corp",
  },
  {
    title: "Сайт магазина ковриков",
    descr:
      'Сайт магазина ковриков "EVADROM".  Было сверстано 7 страниц <a href="project/MatStore/index.html">Главная,</a> <a href="project/MatStore/category.html">Каталог,</a> <a href="project/MatStore/car.html">Каталог марок,</a> <a href="project/MatStore/card.html">Карточка товара,</a> <a href="project/MatStore/basket.html">Корзина,</a> <a href="project/MatStore/offer.html">Оффер</a> и <a href="project/MatStore/thanks.html">Страница Спасибо за покупку</a>.',
    price: "22.000",
    img: require("@/assets/img/portfolio/5.jpg"),
    link: "project/MatStore/index.html",
    site: "shop",
  },
  {
    title: "Сайт магазина мебели",
    descr: 'Сайт магазина мебели "ADORABLE". Было сверстано 22 страницы. Интернет магазин сверстаный с нуля.',
    price: "50.000",
    img: require("@/assets/img/portfolio/11.jpg"),
    link: "project/adorable-mebel/index.html",
    site: "shop",
  },
  {
    title: "Сайт магазина стали",
    descr: 'Сайт магазина стали "Стали Китая". Было сверстано 7 страниц и натянуто на Wordpress для удобного управления сайтом.',
    price: "32.000",
    img: require("@/assets/img/portfolio/12.jpg"),
    link: "https://china-steel.ru/",
    site: "shop",
  },
  {
    title: "Сайт заказа премиум авто",
    descr: 'Сайт заказа премиум авто "Bt one". Стояла задача обновить старый дизайн сайта.',
    price: "11.000",
    img: require("@/assets/img/portfolio/13.jpg"),
    link: "https://bt-one.ru/",
    site: "corp",
  },
  {
    title: "Сайт платформы управления",
    descr: 'Сайт платформы управления "Teamstorm". Стояла задача сверстать блог и натянуть на Wordpress. Было сверстано 3 страницы.',
    price: "13.000",
    img: require("@/assets/img/portfolio/15.jpg"),
    link: "https://blog.teamstorm.io/",
    site: "corp",
  },

  {
    title: "Копия сайта Netflix",
    descr: "Копия сайта Netflix",
    price: "",
    img: require("@/assets/img/portfolio/6.jpg"),
    link: "project/Netflix/index.html",
    site: "landing",
  },
  {
    title: "Cайт агенства недвижимости",
    descr: 'Cайт агенства недвижимости  "Rizon". Было сверстано 2 страницы Главная" и "Форма". Главным условием было сделать анимации.',
    price: "5.500",
    img: require("@/assets/img/portfolio/7.jpg"),
    link: "project/rizon/index.html",
    site: "landing",
  },
  {
    title: "Сайт NFT токена",
    descr: 'На сайте было реализован 1 слайдер библиотека "Slick slider" , была использована библиотека "AOS" анимация так же 4 аккордеона.',
    price: "6.000",
    img: require("@/assets/img/portfolio/8.jpg"),
    link: "project/SpiderShiba/index.html",
    site: "landing",
  },
];
